export * from "./facultyApi";
export * from "./mastersApi";
export * from "./facultyAttendanceApi";
export * from "./facultyLeaveApi";
export * from "./facultyPerformanceApi";
export * from "./facultyRegistrationApi";
export * from "./facultyResearchApi";
export * from "./subjectAllocationApi";
export * from "./workloadRuleApi";
